#pragma once

#define MIN_INT8 CHAR_MIN
#define MAX_INT8 CHAR_MAX

#define MIN_INT16 SHRT_MIN
#define MAX_INT16 SHRT_MAX

#define MIN_INT32 INT_MIN
#define MAX_INR32 INT_MAX

#define MIN_INT64 LLONG_MIN
#define MAX_INT64 LLONG_MAX

#define MIN_UINT8 0
#define MAX_UINT8 255

#define MIN_UINT16 0
#define MAX_UINT16 USHRT_MAX

#define MIN_UINT32 0
#define MAX_UINT32 UINT_MAX

#define MIN_UINT64 0
#define MAX_UINT64 ULLONG_MAX